#!/bin/bash

echo "================================"
echo "Recipe Calories - Database Setup"
echo "================================"
echo ""
echo "SQL Schema file location:"
echo "  /Users/erickpuga/Documents/Personal/devops/app/docs/database-schema.sql"
echo ""
echo "To execute the schema in Supabase:"
echo ""
echo "1. Go to https://supabase.com/dashboard"
echo "2. Select your project"
echo "3. Go to SQL Editor"
echo "4. Click 'New Query'"
echo "5. Copy the contents of database-schema.sql"
echo "6. Paste and click 'Run'"
echo ""
echo "Once the schema is created, the backend will work:"
echo ""
echo "  cd /Users/erickpuga/Documents/Personal/devops/app/backend"
echo "  npm run dev"
echo ""
echo "Then test the endpoints in another terminal:"
echo ""
echo "  bash test.sh"
echo ""
